### ISSUE TITLE
"save tags to the tags path in a model" timeout.

### ISSUE THREAD

**Issue by wanguolin** [joeyfromspace/mongoose-tag-everything#1]
When I'm trying to add tags for my movie database, I found this module and thought this may very useful for my movie mongoDB's tag searching. But I'm failed with

>  Model.create({ name: 'Lorem Ipsum', tags: ['cool', 'rad'] }, function(err, doc) {
>       assert.deepEqual(_.map(doc.tags, 'name'), ['cool', 'rad']);

The strange thing is, the code is exactly same with the test case, even I've copied the test case to my project folder, run as "mocha schema.js", it failed as well, shows:

> 1 passing (4s)
>   6 failing
> 
>   1) mongoose-tag-everything should save tags to the tags path in a model:
>      Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

As I have looked into the mongoose_tag_everything.js, the differences between the successful npm test and mocha schema.js is the 

> Tag.create({ name: tag }, function(err, tagModel) {
>             return next(err, tagModel);
>           });
> 

has not been invoked.. I've both tried mongoDB running on both Linux and Windows, same issue.

So could you please share your knowage about how to fix this issue?

Thanks.

**Comment by joeyfromspace** [comment]
This seems to be an issue between certain mongoose configurations and asynchronous functions in middleware. I'm currently trying to find a workaround for it and will hopefully have an updated version in a few days. 

Thanks for bringing this issue to my attention!

**Comment by joeyfromspace** [comment]
I discovered the cause of this. The issue is when you create a Mongoose connection inside of a closure and do not use the default connection in the global namespace. This causes the tags plugin to load on its own connection, where the schema it's mounted to is not defined.

I've developed a workaround for this by allowing you to pass in the mongoose object you want the plugin to use in options. Ideally, the plugin should use the same mongoose instance as the schema but for whatever reason this is not the case.
